default_language_version:
    python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.46.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [pre-commit]
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx --prefix frontend prettier --write
        language: system
        files: ^frontend/.*\.(js|jsx|ts|tsx|css|scss|json)$
      - id: eslint
        name: eslint
        entry: npx --prefix frontend eslint --fix --config frontend/eslint.config.js
        language: system
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
