[project]
name = "xscattering-backend"
version = "0.1.0"
description = "FastAPI backend for X-ray scattering analysis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fabio>=2025.10.0",
    "fastapi[standard]>=0.124.0",
    "msgpack>=1.1.2",
    "numpy>=2.3.5",
    "pyfai==2025.12.1",
    "python-dotenv>=1.2.1",
    "tiled[client]==0.1.0b16",
]

[project.scripts]
xscattering-backend = "main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["routers", "utils"]

[tool.hatch.build.targets.wheel.sources]
"" = ""

[tool.hatch.build.targets.sdist]
include = ["main.py", "routers/", "utils/"]
